import type { ToolDefinition } from "@/types/registry";

export const networkTools: ToolDefinition[] = [
  {
    id: "network-ip-parser",
    slug: "ip-parser",
    name: "IP Address Parser",
    shortDescription: "Parse IPv4 or IPv6 addresses and show type, hex, binary, and decimal.",
    description: "Parse and analyze IPv4 and IPv6 addresses. Shows address type (private, loopback, multicast, public), decimal, hex, and binary representations.",
    category: "network",
    tags: ["ip", "ipv4", "ipv6", "network", "address", "subnet"],
    keywords: ["ip address parser online", "ipv4 analyzer", "ip address type checker"],
    icon: "Network",
    status: "new",
    component: () => import("@/tools/network/ip-parser"),
    process: (input) => import("@/tools/network/ip-parser/logic").then((m) => m.process(input)),
  },
  {
    id: "network-url-parser",
    slug: "url-parser",
    name: "URL Parser",
    shortDescription: "Break a URL into its components: protocol, host, path, query params, and hash.",
    description: "Parse any URL into its components: protocol, username, password, hostname, port, pathname, query parameters, and fragment. Also lists all query string parameters.",
    category: "network",
    tags: ["url", "uri", "parse", "query", "parameters", "network"],
    keywords: ["url parser online", "url decompose", "parse url parameters"],
    icon: "Link",
    status: "new",
    component: () => import("@/tools/network/url-parser"),
    process: (input) => import("@/tools/network/url-parser/logic").then((m) => m.process(input)),
  },
  {
    id: "network-defang",
    slug: "defang",
    name: "Defang / Refang URLs & IPs",
    shortDescription: "Make URLs and IPs safe to share in reports by defanging them.",
    description: "Defang URLs (hXXps://example[.]com) and IPs (192[.]168[.]1[.]1) to make them safe for inclusion in threat reports and emails. Also refangs defanged indicators.",
    category: "network",
    tags: ["defang", "refang", "url", "ip", "ioc", "threat", "security"],
    keywords: ["defang url online", "defang ip address", "ioc defang tool"],
    icon: "ShieldOff",
    status: "new",
    component: () => import("@/tools/network/defang"),
    process: (input) => import("@/tools/network/defang/logic").then((m) => m.process(input)),
  },
  {
    id: "network-mac-lookup",
    slug: "mac-formatter",
    name: "MAC Address Formatter",
    shortDescription: "Convert MAC addresses between colon, hyphen, dot, and plain formats.",
    description: "Parse a MAC address in any format and display it in all common formats: colon-separated, hyphen-separated, Cisco dot notation, and plain hex. Also shows the OUI prefix.",
    category: "network",
    tags: ["mac", "address", "ethernet", "oui", "network", "format"],
    keywords: ["mac address formatter online", "mac address converter", "ethernet address"],
    icon: "Cpu",
    status: "new",
    component: () => import("@/tools/network/mac-lookup"),
    process: (input) => import("@/tools/network/mac-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "network-extract-ips",
    slug: "extract-ips",
    name: "Extract IP Addresses",
    shortDescription: "Extract all IPv4 and IPv6 addresses from a block of text.",
    description: "Scan a body of text and extract all IPv4 and IPv6 addresses. Useful for parsing log files, emails, or threat intelligence reports.",
    category: "network",
    tags: ["extract", "ip", "ipv4", "ipv6", "log", "forensics"],
    keywords: ["extract ip addresses from text", "ip extractor online"],
    icon: "ScanLine",
    status: "new",
    component: () => import("@/tools/network/extract-ips"),
    process: (input) => import("@/tools/network/extract-ips/logic").then((m) => m.process(input)),
  },
  {
    id: "network-extract-urls",
    slug: "extract-urls",
    name: "Extract URLs",
    shortDescription: "Extract all URLs from a block of text.",
    description: "Scan a block of text and extract all http:// and https:// URLs. Useful for parsing web pages, emails, logs, or documents.",
    category: "network",
    tags: ["extract", "url", "links", "scrape", "forensics"],
    keywords: ["extract urls from text online", "url extractor"],
    icon: "Link2",
    status: "new",
    component: () => import("@/tools/network/extract-urls"),
    process: (input) => import("@/tools/network/extract-urls/logic").then((m) => m.process(input)),
  },
  {
    id: "network-extract-emails",
    slug: "extract-emails",
    name: "Extract Email Addresses",
    shortDescription: "Extract all email addresses from a block of text.",
    description: "Scan a block of text and extract all email addresses. Useful for parsing logs, documents, or any unstructured text containing contact information.",
    category: "network",
    tags: ["extract", "email", "addresses", "scrape", "forensics"],
    keywords: ["extract email addresses from text", "email extractor online"],
    icon: "Mail",
    status: "new",
    component: () => import("@/tools/network/extract-emails"),
    process: (input) => import("@/tools/network/extract-emails/logic").then((m) => m.process(input)),
  },
];
