import type { ToolDefinition } from "@/types/registry";

export const networkTools: ToolDefinition[] = [
  {
    id: "network-ip-parser",
    slug: "ip-parser",
    name: "IP Address Parser",
    shortDescription: "Parse IPv4 or IPv6 addresses and show type, hex, binary, and decimal.",
    description: "Parse and analyze IPv4 and IPv6 addresses. Shows address type (private, loopback, multicast, public), decimal, hex, and binary representations.",
    category: "network",
    tags: ["ip", "ipv4", "ipv6", "network", "address", "subnet"],
    keywords: ["ip address parser online", "ipv4 analyzer", "ip address type checker"],
    icon: "Network",
    status: "new",
    component: () => import("@/tools/network/ip-parser"),
    process: (input) => import("@/tools/network/ip-parser/logic").then((m) => m.process(input)),
  },
  {
    id: "network-url-parser",
    slug: "url-parser",
    name: "URL Parser",
    shortDescription: "Break a URL into its components: protocol, host, path, query params, and hash.",
    description: "Parse any URL into its components: protocol, username, password, hostname, port, pathname, query parameters, and fragment. Also lists all query string parameters.",
    category: "network",
    tags: ["url", "uri", "parse", "query", "parameters", "network"],
    keywords: ["url parser online", "url decompose", "parse url parameters"],
    icon: "Link",
    status: "new",
    component: () => import("@/tools/network/url-parser"),
    process: (input) => import("@/tools/network/url-parser/logic").then((m) => m.process(input)),
  },
  {
    id: "network-defang",
    slug: "defang",
    name: "Defang / Refang URLs & IPs",
    shortDescription: "Make URLs and IPs safe to share in reports by defanging them.",
    description: "Defang URLs (hXXps://example[.]com) and IPs (192[.]168[.]1[.]1) to make them safe for inclusion in threat reports and emails. Also refangs defanged indicators.",
    category: "network",
    tags: ["defang", "refang", "url", "ip", "ioc", "threat", "security"],
    keywords: ["defang url online", "defang ip address", "ioc defang tool"],
    icon: "ShieldOff",
    status: "new",
    component: () => import("@/tools/network/defang"),
    process: (input) => import("@/tools/network/defang/logic").then((m) => m.process(input)),
  },
  {
    id: "network-mac-lookup",
    slug: "mac-formatter",
    name: "MAC Address Formatter",
    shortDescription: "Convert MAC addresses between colon, hyphen, dot, and plain formats.",
    description: "Parse a MAC address in any format and display it in all common formats: colon-separated, hyphen-separated, Cisco dot notation, and plain hex. Also shows the OUI prefix.",
    category: "network",
    tags: ["mac", "address", "ethernet", "oui", "network", "format"],
    keywords: ["mac address formatter online", "mac address converter", "ethernet address"],
    icon: "Cpu",
    status: "new",
    component: () => import("@/tools/network/mac-lookup"),
    process: (input) => import("@/tools/network/mac-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "network-extract-ips",
    slug: "extract-ips",
    name: "Extract IP Addresses",
    shortDescription: "Extract all IPv4 and IPv6 addresses from a block of text.",
    description: "Scan a body of text and extract all IPv4 and IPv6 addresses. Useful for parsing log files, emails, or threat intelligence reports.",
    category: "network",
    tags: ["extract", "ip", "ipv4", "ipv6", "log", "forensics"],
    keywords: ["extract ip addresses from text", "ip extractor online"],
    icon: "ScanLine",
    status: "new",
    component: () => import("@/tools/network/extract-ips"),
    process: (input) => import("@/tools/network/extract-ips/logic").then((m) => m.process(input)),
  },
  {
    id: "network-extract-urls",
    slug: "extract-urls",
    name: "Extract URLs",
    shortDescription: "Extract all URLs from a block of text.",
    description: "Scan a block of text and extract all http:// and https:// URLs. Useful for parsing web pages, emails, logs, or documents.",
    category: "network",
    tags: ["extract", "url", "links", "scrape", "forensics"],
    keywords: ["extract urls from text online", "url extractor"],
    icon: "Link2",
    status: "new",
    component: () => import("@/tools/network/extract-urls"),
    process: (input) => import("@/tools/network/extract-urls/logic").then((m) => m.process(input)),
  },
  {
    id: "network-extract-emails",
    slug: "extract-emails",
    name: "Extract Email Addresses",
    shortDescription: "Extract all email addresses from a block of text.",
    description: "Scan a block of text and extract all email addresses. Useful for parsing logs, documents, or any unstructured text containing contact information.",
    category: "network",
    tags: ["extract", "email", "addresses", "scrape", "forensics"],
    keywords: ["extract email addresses from text", "email extractor online"],
    icon: "Mail",
    status: "new",
    component: () => import("@/tools/network/extract-emails"),
    process: (input) => import("@/tools/network/extract-emails/logic").then((m) => m.process(input)),
  },
  {
    id: "network-dns-lookup",
    slug: "dns-lookup",
    name: "DNS Lookup",
    shortDescription: "Query any DNS record type for a domain using DNS-over-HTTPS.",
    description: "Look up A, AAAA, MX, CNAME, TXT, NS, SOA, SRV, PTR, CAA, DNSKEY, DS, CERT, LOC, IPSECKEY, RRSIG, NSEC, NSEC3PARAM, and more record types via DNS-over-HTTPS.",
    category: "network",
    tags: ["dns", "lookup", "a", "aaaa", "mx", "cname", "txt", "ns", "soa", "srv", "ptr"],
    keywords: ["dns lookup online", "dns record checker", "dns query tool"],
    icon: "Globe",
    status: "new",
    component: () => import("@/tools/network/dns-lookup"),
    process: (input) => import("@/tools/network/dns-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "network-whois",
    slug: "whois",
    name: "WHOIS Lookup",
    shortDescription: "Look up domain registration and ownership details via RDAP.",
    description: "Query WHOIS / RDAP data for any domain: registrar, creation/expiry dates, name servers, registrant info, and status flags.",
    category: "network",
    tags: ["whois", "rdap", "domain", "registration", "registrar", "nameserver"],
    keywords: ["whois lookup online", "domain whois checker", "rdap lookup"],
    icon: "Search",
    status: "new",
    component: () => import("@/tools/network/whois"),
    process: (input) => import("@/tools/network/whois/logic").then((m) => m.process(input)),
  },
  {
    id: "network-subnet-calc",
    slug: "subnet-calculator",
    name: "Subnet Calculator",
    shortDescription: "Calculate network and host ranges from a CIDR or IP + mask.",
    description: "Enter an IP address with CIDR notation or subnet mask to get network address, broadcast address, first/last usable hosts, number of hosts, wildcard mask, and binary breakdown.",
    category: "network",
    tags: ["subnet", "cidr", "ip", "mask", "network", "broadcast", "calculator"],
    keywords: ["subnet calculator online", "cidr calculator", "ip subnet tool"],
    icon: "Calculator",
    status: "new",
    component: () => import("@/tools/network/subnet-calc"),
    process: (input) => import("@/tools/network/subnet-calc/logic").then((m) => m.process(input)),
  },
  {
    id: "network-blacklist-check",
    slug: "blacklist-check",
    name: "IP Blacklist Check",
    shortDescription: "Check if an IP address appears on 15 common DNS blacklists.",
    description: "Check an IP address against 15 major DNS-based blacklists (RBLs) including Spamhaus ZEN, Barracuda, SORBS, and more using DNS-over-HTTPS.",
    category: "network",
    tags: ["blacklist", "rbl", "spam", "ip", "blocklist", "dnsbl"],
    keywords: ["ip blacklist check online", "rbl checker", "spam blacklist lookup"],
    icon: "ShieldAlert",
    status: "new",
    component: () => import("@/tools/network/blacklist-check"),
    process: (input) => import("@/tools/network/blacklist-check/logic").then((m) => m.process(input)),
  },
  {
    id: "network-http-headers",
    slug: "http-headers",
    name: "HTTP Headers Checker",
    shortDescription: "Inspect HTTP response headers and audit security headers.",
    description: "Fetch HTTP response headers for any URL and audit security headers: Content-Security-Policy, HSTS, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy, and X-XSS-Protection.",
    category: "network",
    tags: ["http", "headers", "security", "csp", "hsts", "cors", "web"],
    keywords: ["http headers checker online", "security headers test", "http response headers"],
    icon: "FileCode",
    status: "new",
    component: () => import("@/tools/network/http-headers"),
    process: (input) => import("@/tools/network/http-headers/logic").then((m) => m.process(input)),
  },
  {
    id: "network-my-ip",
    slug: "my-ip",
    name: "What Is My IP",
    shortDescription: "Detect your public IPv4 and IPv6 addresses.",
    description: "Instantly detect your public IPv4 and IPv6 addresses using ipify.org. No data is stored.",
    category: "network",
    tags: ["ip", "my ip", "public ip", "ipv4", "ipv6", "what is my ip"],
    keywords: ["what is my ip address", "my public ip online", "check ip address"],
    icon: "MapPin",
    status: "new",
    component: () => import("@/tools/network/my-ip"),
    process: (input) => import("@/tools/network/my-ip/logic").then((m) => m.process(input)),
  },
  {
    id: "network-dns-propagation",
    slug: "dns-propagation",
    name: "DNS Propagation Check",
    shortDescription: "Check DNS propagation across Google, Cloudflare, and Quad9.",
    description: "Query a domain's DNS records simultaneously from Google, Cloudflare, and Quad9 resolvers to see if changes have propagated worldwide.",
    category: "network",
    tags: ["dns", "propagation", "check", "cloudflare", "google", "quad9", "resolver"],
    keywords: ["dns propagation checker online", "dns propagation tool", "global dns lookup"],
    icon: "Radio",
    status: "new",
    component: () => import("@/tools/network/dns-propagation"),
    process: (input) => import("@/tools/network/dns-propagation/logic").then((m) => m.process(input)),
  },
  {
    id: "network-asn-lookup",
    slug: "asn-lookup",
    name: "ASN Lookup",
    shortDescription: "Look up ASN, organization, and geolocation for an IP address.",
    description: "Enter an IP address to look up its Autonomous System Number (ASN), organization, country, city, and hostname via ipinfo.io.",
    category: "network",
    tags: ["asn", "ip", "geolocation", "organization", "isp", "lookup"],
    keywords: ["asn lookup online", "ip asn lookup", "ip geolocation tool"],
    icon: "Building2",
    status: "new",
    component: () => import("@/tools/network/asn-lookup"),
    process: (input) => import("@/tools/network/asn-lookup/logic").then((m) => m.process(input)),
  },
];
