import type { ToolDefinition } from "@/types/registry";

export const emailTools: ToolDefinition[] = [
  {
    id: "email-mx-lookup",
    slug: "mx-lookup",
    name: "MX Lookup",
    shortDescription: "Look up MX records for a domain to find its mail servers.",
    description: "Query DNS MX records for any domain to see its mail servers and their priorities. Uses DNS-over-HTTPS for accurate results.",
    category: "email",
    tags: ["mx", "dns", "mail", "email", "lookup", "smtp"],
    keywords: ["mx lookup online", "mail exchanger lookup", "dns mx record checker"],
    icon: "Mail",
    status: "new",
    component: () => import("@/tools/email/mx-lookup"),
    process: (input) => import("@/tools/email/mx-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "email-spf-lookup",
    slug: "spf-lookup",
    name: "SPF Lookup",
    shortDescription: "Check SPF records for a domain and parse the policy.",
    description: "Fetch and parse Sender Policy Framework (SPF) TXT records. Shows mechanisms, qualifiers, include depth, and potential issues with the policy.",
    category: "email",
    tags: ["spf", "dns", "email", "authentication", "sender policy", "txt"],
    keywords: ["spf lookup online", "spf record checker", "sender policy framework lookup"],
    icon: "ShieldCheck",
    status: "new",
    component: () => import("@/tools/email/spf-lookup"),
    process: (input) => import("@/tools/email/spf-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "email-dmarc-lookup",
    slug: "dmarc-lookup",
    name: "DMARC Lookup",
    shortDescription: "Check DMARC policy for a domain.",
    description: "Look up and parse DMARC records at _dmarc.yourdomain.com. Shows policy (p=), subdomain policy (sp=), percentage (pct=), report URIs, and alignment modes.",
    category: "email",
    tags: ["dmarc", "dns", "email", "authentication", "policy", "txt"],
    keywords: ["dmarc lookup online", "dmarc record checker", "dmarc policy check"],
    icon: "ShieldAlert",
    status: "new",
    component: () => import("@/tools/email/dmarc-lookup"),
    process: (input) => import("@/tools/email/dmarc-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "email-dkim-lookup",
    slug: "dkim-lookup",
    name: "DKIM Lookup",
    shortDescription: "Look up DKIM public key for a domain and selector.",
    description: "Query DKIM TXT records at {selector}._domainkey.{domain}. Parses the public key, algorithm, key type, and flags. Includes common selectors to try.",
    category: "email",
    tags: ["dkim", "dns", "email", "authentication", "signature", "public key"],
    keywords: ["dkim lookup online", "dkim record checker", "dkim key lookup"],
    icon: "Key",
    status: "new",
    component: () => import("@/tools/email/dkim-lookup"),
    process: (input) => import("@/tools/email/dkim-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "email-bimi-lookup",
    slug: "bimi-lookup",
    name: "BIMI Lookup",
    shortDescription: "Look up BIMI record for a domain's brand logo indicator.",
    description: "Query BIMI (Brand Indicators for Message Identification) DNS records. Shows the logo URL (SVG) and optional Verified Mark Certificate (VMC) URL.",
    category: "email",
    tags: ["bimi", "dns", "email", "brand", "logo", "indicator"],
    keywords: ["bimi lookup online", "bimi record checker", "brand indicators email"],
    icon: "Image",
    status: "new",
    component: () => import("@/tools/email/bimi-lookup"),
    process: (input) => import("@/tools/email/bimi-lookup/logic").then((m) => m.process(input)),
  },
  {
    id: "email-mta-sts",
    slug: "mta-sts",
    name: "MTA-STS Lookup",
    shortDescription: "Check MTA-STS policy for a domain to enforce TLS for email.",
    description: "Look up MTA-STS DNS record and fetch the full policy file from .well-known/mta-sts.txt. Shows mode, MX hosts, max age, and the raw policy.",
    category: "email",
    tags: ["mta-sts", "tls", "email", "security", "smtp", "dns"],
    keywords: ["mta-sts lookup online", "mta-sts record checker", "smtp tls policy"],
    icon: "Lock",
    status: "new",
    component: () => import("@/tools/email/mta-sts"),
    process: (input) => import("@/tools/email/mta-sts/logic").then((m) => m.process(input)),
  },
  {
    id: "email-tlsrpt",
    slug: "tlsrpt",
    name: "TLSRPT Lookup",
    shortDescription: "Look up SMTP TLS Reporting (TLSRPT) record for a domain.",
    description: "Fetch the TLS-RPT DNS record at _smtp._tls.{domain}. Shows the report URIs (rua) where TLS failure reports are sent.",
    category: "email",
    tags: ["tlsrpt", "tls", "email", "reporting", "smtp", "dns"],
    keywords: ["tlsrpt lookup online", "smtp tls reporting check", "tls-rpt record"],
    icon: "FileText",
    status: "new",
    component: () => import("@/tools/email/tlsrpt"),
    process: (input) => import("@/tools/email/tlsrpt/logic").then((m) => m.process(input)),
  },
  {
    id: "email-header-analyzer",
    slug: "email-header-analyzer",
    name: "Email Header Analyzer",
    shortDescription: "Paste raw email headers to analyze routing, delays, and auth results.",
    description: "Parse raw email headers to extract sender, recipient, subject, SPF/DKIM/DMARC results, and the full delivery hop chain with per-hop timing.",
    category: "email",
    tags: ["email", "headers", "analyze", "spf", "dkim", "dmarc", "routing", "delay"],
    keywords: ["email header analyzer online", "email header parser", "analyze email headers"],
    icon: "FileSearch",
    status: "new",
    component: () => import("@/tools/email/email-header-analyzer"),
    process: (input) => import("@/tools/email/email-header-analyzer/logic").then((m) => m.process(input)),
  },
  {
    id: "email-spf-generator",
    slug: "spf-generator",
    name: "SPF Record Generator",
    shortDescription: "Build a valid SPF TXT record from a form.",
    description: "Generate an SPF TXT record by selecting your policy, adding include domains, allowed IP ranges, and choosing whether to include MX/A records.",
    category: "email",
    tags: ["spf", "generator", "email", "authentication", "dns", "txt"],
    keywords: ["spf record generator online", "create spf record", "spf builder"],
    icon: "FilePlus",
    status: "new",
    component: () => import("@/tools/email/spf-generator"),
    process: (input) => import("@/tools/email/spf-generator/logic").then((m) => m.process(input)),
  },
  {
    id: "email-dmarc-generator",
    slug: "dmarc-generator",
    name: "DMARC Record Generator",
    shortDescription: "Build a valid DMARC TXT record from a form.",
    description: "Generate a DMARC TXT record by selecting policy, subdomain policy, percentage, report URIs, and SPF/DKIM alignment modes.",
    category: "email",
    tags: ["dmarc", "generator", "email", "authentication", "dns", "txt"],
    keywords: ["dmarc record generator online", "create dmarc record", "dmarc builder"],
    icon: "FilePlus2",
    status: "new",
    component: () => import("@/tools/email/dmarc-generator"),
    process: (input) => import("@/tools/email/dmarc-generator/logic").then((m) => m.process(input)),
  },
  {
    id: "email-domain-health",
    slug: "domain-health",
    name: "Domain Health Check",
    shortDescription: "Run a full email health report for a domain.",
    description: "Check a domain's email health by verifying MX records, SPF, DMARC, BIMI, MTA-STS, TLSRPT, and NS records. Returns a health score and per-check status.",
    category: "email",
    tags: ["domain", "health", "email", "mx", "spf", "dmarc", "bimi", "mta-sts", "tlsrpt"],
    keywords: ["domain health check online", "email health report", "email configuration checker"],
    icon: "HeartPulse",
    status: "new",
    component: () => import("@/tools/email/domain-health"),
    process: (input) => import("@/tools/email/domain-health/logic").then((m) => m.process(input)),
  },
];
