import type { ToolCategory } from "@/types/registry";

export const CATEGORIES: ToolCategory[] = [
  {
    id: "json",
    name: "JSON Tools",
    description: "Validate, format, convert, and transform JSON data",
    icon: "Braces",
    color: "amber",
    slug: "json",
    order: 1,
  },
  {
    id: "generators",
    name: "Generators",
    description: "Generate QR codes, barcodes, and other visual assets",
    icon: "QrCode",
    color: "violet",
    slug: "generators",
    order: 2,
  },
  {
    id: "encoding",
    name: "Encoding & Hashing",
    description: "Encode, decode, and hash data in various formats",
    icon: "Binary",
    color: "blue",
    slug: "encoding",
    order: 3,
  },
  {
    id: "cryptography",
    name: "Cryptography",
    description: "Classical ciphers, XOR, and encryption tools",
    icon: "KeyRound",
    color: "red",
    slug: "cryptography",
    order: 4,
  },
  {
    id: "network",
    name: "Network",
    description: "DNS lookups, WHOIS, subnet calculator, and network diagnostics",
    icon: "Globe",
    color: "cyan",
    slug: "network",
    order: 5,
  },
  {
    id: "email",
    name: "Email & DNS",
    description: "MX, SPF, DMARC, DKIM lookups and email header analysis",
    icon: "Mail",
    color: "indigo",
    slug: "email",
    order: 6,
  },
  {
    id: "text",
    name: "Text",
    description: "String manipulation, transformation, and analysis tools",
    icon: "Type",
    color: "orange",
    slug: "text",
    order: 7,
  },
  {
    id: "datetime",
    name: "Date / Time",
    description: "Timestamp conversion, date formatting, and time utilities",
    icon: "Calendar",
    color: "teal",
    slug: "datetime",
    order: 8,
  },
  {
    id: "certificates",
    name: "Certificates",
    description: "Decode, generate, and convert SSL/TLS certificates and keys",
    icon: "ShieldCheck",
    color: "green",
    slug: "certificates",
    order: 9,
  },
];
