import type { ToolDefinition } from "@/types/registry";

export const textTools: ToolDefinition[] = [
  {
    id: "text-case-converter",
    slug: "case-converter",
    name: "Case Converter",
    shortDescription: "Convert text between UPPER, lower, Title, camelCase, snake_case, and more.",
    description: "Transform text between 12 different case formats: UPPER, lower, Title, Sentence, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, dot.case, aLtErNaTiNg, and iNVERSE.",
    category: "text",
    tags: ["case", "convert", "camel", "snake", "kebab", "pascal", "upper", "lower"],
    keywords: ["case converter online", "camelcase to snake_case", "text case changer"],
    icon: "CaseSensitive",
    status: "new",
    component: () => import("@/tools/text/case-converter"),
    process: (input) => import("@/tools/text/case-converter/logic").then((m) => m.process(input)),
  },
  {
    id: "text-find-replace",
    slug: "find-replace",
    name: "Find & Replace",
    shortDescription: "Find and replace text with optional regex, case sensitivity, and global mode.",
    description: "Search for text patterns and replace them. Supports plain text or regular expressions, case-sensitive or insensitive matching, and single or global replacement.",
    category: "text",
    tags: ["find", "replace", "regex", "search", "substitute"],
    keywords: ["find and replace online", "regex replace tool", "text substitution"],
    icon: "Replace",
    status: "new",
    component: () => import("@/tools/text/find-replace"),
    process: (input) => import("@/tools/text/find-replace/logic").then((m) => m.process(input)),
  },
  {
    id: "text-sort-lines",
    slug: "sort-lines",
    name: "Sort Lines",
    shortDescription: "Sort lines alphabetically, numerically, or in reverse.",
    description: "Sort lines of text alphabetically (ascending or descending), with optional natural number sorting, case-insensitive matching, and deduplication.",
    category: "text",
    tags: ["sort", "lines", "alphabetical", "order", "unique"],
    keywords: ["sort lines online", "sort text alphabetically", "line sorter"],
    icon: "ArrowUpDown",
    status: "new",
    component: () => import("@/tools/text/sort-lines"),
    process: (input) => import("@/tools/text/sort-lines/logic").then((m) => m.process(input)),
  },
  {
    id: "text-remove-duplicates",
    slug: "remove-duplicates",
    name: "Remove Duplicate Lines",
    shortDescription: "Remove duplicate lines from text, with optional case-insensitive matching.",
    description: "Remove duplicate lines from a block of text. Options include case-insensitive matching, trimming whitespace before comparison, and removing empty lines.",
    category: "text",
    tags: ["duplicate", "unique", "lines", "deduplicate", "filter"],
    keywords: ["remove duplicate lines online", "unique lines tool", "deduplicate text"],
    icon: "ListX",
    status: "new",
    component: () => import("@/tools/text/remove-duplicates"),
    process: (input) => import("@/tools/text/remove-duplicates/logic").then((m) => m.process(input)),
  },
  {
    id: "text-filter-lines",
    slug: "filter-lines",
    name: "Filter Lines",
    shortDescription: "Keep or remove lines that match a pattern or regex.",
    description: "Filter lines of text by a search pattern. Include only matching lines (grep-like) or exclude matching lines. Supports plain text and regular expressions.",
    category: "text",
    tags: ["filter", "grep", "lines", "regex", "include", "exclude"],
    keywords: ["filter lines online", "grep text online", "line filter tool"],
    icon: "Filter",
    status: "new",
    component: () => import("@/tools/text/filter-lines"),
    process: (input) => import("@/tools/text/filter-lines/logic").then((m) => m.process(input)),
  },
  {
    id: "text-word-count",
    slug: "word-count",
    name: "Word Count",
    shortDescription: "Count words, characters, lines, sentences, and paragraphs.",
    description: "Analyze text statistics: word count, character count (with and without spaces), line count, sentence count, paragraph count, unique words, average word length, and estimated reading time.",
    category: "text",
    tags: ["word count", "characters", "lines", "statistics", "analysis"],
    keywords: ["word counter online", "character counter", "text statistics"],
    icon: "BarChart2",
    status: "new",
    component: () => import("@/tools/text/word-count"),
    process: (input) => import("@/tools/text/word-count/logic").then((m) => m.process(input)),
  },
  {
    id: "text-reverse",
    slug: "reverse",
    name: "Reverse Text",
    shortDescription: "Reverse characters, words, or lines.",
    description: "Reverse text by characters (mirror the entire string), by words (reverse word order), or by lines (reverse line order).",
    category: "text",
    tags: ["reverse", "mirror", "text", "words", "lines"],
    keywords: ["reverse text online", "reverse string", "mirror text"],
    icon: "FlipHorizontal",
    status: "new",
    component: () => import("@/tools/text/reverse"),
    process: (input) => import("@/tools/text/reverse/logic").then((m) => m.process(input)),
  },
  {
    id: "text-diff",
    slug: "diff",
    name: "Text Diff",
    shortDescription: "Compare two texts side-by-side and highlight added, removed, and unchanged lines.",
    description: "Paste two versions of a text and instantly see the line-by-line differences. Added lines are highlighted green, removed lines red. Supports split and unified views, ignore whitespace, and ignore case options.",
    category: "text",
    tags: ["diff", "compare", "difference", "lines", "side-by-side", "text compare"],
    keywords: ["text diff online", "compare two texts", "text comparison tool", "diff checker"],
    icon: "GitCompare",
    status: "new",
    component: () => import("@/tools/text/diff"),
    process: (input) => import("@/tools/text/diff/logic").then((m) => m.process(input)),
  },
  {
    id: "text-add-line-numbers",
    slug: "add-line-numbers",
    name: "Add Line Numbers",
    shortDescription: "Prefix each line with its line number.",
    description: "Add line numbers to each line of text. Configure the start number, separator string, and whether to zero-pad numbers for alignment.",
    category: "text",
    tags: ["line numbers", "prefix", "numbering", "format"],
    keywords: ["add line numbers online", "number lines tool"],
    icon: "ListOrdered",
    status: "new",
    component: () => import("@/tools/text/add-line-numbers"),
    process: (input) => import("@/tools/text/add-line-numbers/logic").then((m) => m.process(input)),
  },
];
