import type { ToolDefinition } from "@/types/registry";

export const cryptographyTools: ToolDefinition[] = [
  {
    id: "crypto-caesar",
    slug: "caesar",
    name: "Caesar / ROT13 Cipher",
    shortDescription: "Encrypt or decrypt text using the Caesar shift cipher.",
    description: "Apply a Caesar cipher (shift cipher) to text with a configurable shift amount. ROT13 is a special case with shift=13. Non-alphabetic characters are preserved.",
    category: "cryptography",
    tags: ["caesar", "rot13", "cipher", "shift", "encrypt", "decrypt"],
    keywords: ["caesar cipher online", "rot13 encoder", "shift cipher"],
    icon: "RotateCw",
    status: "new",
    component: () => import("@/tools/cryptography/caesar"),
    process: (input) => import("@/tools/cryptography/caesar/logic").then((m) => m.process(input)),
  },
  {
    id: "crypto-rot47",
    slug: "rot47",
    name: "ROT47",
    shortDescription: "Apply ROT47 rotation to all printable ASCII characters.",
    description: "ROT47 rotates all 94 printable ASCII characters (! through ~) by 47 positions. Unlike ROT13, it encodes digits and symbols too. Applying it twice returns the original text.",
    category: "cryptography",
    tags: ["rot47", "rotation", "cipher", "ascii", "obfuscation"],
    keywords: ["rot47 encoder decoder", "rot47 cipher online"],
    icon: "RefreshCw",
    status: "new",
    component: () => import("@/tools/cryptography/rot47"),
    process: (input) => import("@/tools/cryptography/rot47/logic").then((m) => m.process(input)),
  },
  {
    id: "crypto-vigenere",
    slug: "vigenere",
    name: "Vigenère Cipher",
    shortDescription: "Encrypt or decrypt text using the Vigenère polyalphabetic cipher.",
    description: "The Vigenère cipher uses a keyword to apply multiple Caesar shifts. Each letter of the message is shifted by the corresponding letter of the repeating key.",
    category: "cryptography",
    tags: ["vigenere", "polyalphabetic", "cipher", "encrypt", "decrypt"],
    keywords: ["vigenere cipher online", "polyalphabetic cipher encoder"],
    icon: "Key",
    status: "new",
    component: () => import("@/tools/cryptography/vigenere"),
    process: (input) => import("@/tools/cryptography/vigenere/logic").then((m) => m.process(input)),
  },
  {
    id: "crypto-atbash",
    slug: "atbash",
    name: "Atbash Cipher",
    shortDescription: "Apply the Atbash cipher — A↔Z, B↔Y, C↔X, etc.",
    description: "The Atbash cipher maps each letter to its reverse in the alphabet (A→Z, B→Y, …). It is its own inverse — encoding and decoding are the same operation.",
    category: "cryptography",
    tags: ["atbash", "cipher", "substitution", "reverse"],
    keywords: ["atbash cipher online", "reverse alphabet cipher"],
    icon: "ArrowLeftRight",
    status: "new",
    component: () => import("@/tools/cryptography/atbash"),
    process: (input) => import("@/tools/cryptography/atbash/logic").then((m) => m.process(input)),
  },
  {
    id: "crypto-xor",
    slug: "xor",
    name: "XOR Cipher",
    shortDescription: "XOR text against a key — supports UTF-8, hex, or decimal keys.",
    description: "XOR each byte of the input against a repeating key. Key can be UTF-8 text, hex bytes, or decimal values. Output can be hex or UTF-8.",
    category: "cryptography",
    tags: ["xor", "cipher", "bitwise", "encrypt", "decrypt"],
    keywords: ["xor cipher online", "xor encrypt decrypt"],
    icon: "Zap",
    status: "new",
    component: () => import("@/tools/cryptography/xor"),
    process: (input) => import("@/tools/cryptography/xor/logic").then((m) => m.process(input)),
  },
  {
    id: "crypto-morse",
    slug: "morse-code",
    name: "Morse Code",
    shortDescription: "Encode text to Morse code or decode Morse code back to text.",
    description: "Convert text to international Morse code (dots and dashes) or decode Morse code back to text. Letters are separated by spaces, words by /.",
    category: "cryptography",
    tags: ["morse", "dots", "dashes", "encode", "decode", "radio"],
    keywords: ["morse code translator", "morse code encoder decoder online"],
    icon: "Radio",
    status: "new",
    component: () => import("@/tools/cryptography/morse"),
    process: (input) => import("@/tools/cryptography/morse/logic").then((m) => m.process(input)),
  },
  {
    id: "crypto-nato",
    slug: "nato-alphabet",
    name: "NATO Phonetic Alphabet",
    shortDescription: "Convert text to NATO phonetic alphabet words or reverse.",
    description: "Spell out text using the NATO phonetic alphabet (Alpha, Bravo, Charlie, …) for unambiguous voice communication. Also decodes NATO words back to text.",
    category: "cryptography",
    tags: ["nato", "phonetic", "alphabet", "military", "radio"],
    keywords: ["nato phonetic alphabet converter", "phonetic alphabet encoder"],
    icon: "Mic",
    status: "new",
    component: () => import("@/tools/cryptography/nato"),
    process: (input) => import("@/tools/cryptography/nato/logic").then((m) => m.process(input)),
  },
  {
    id: "crypto-a1z26",
    slug: "a1z26",
    name: "A1Z26 Cipher",
    shortDescription: "Substitute letters with their position in the alphabet (A=1, B=2, …).",
    description: "The A1Z26 cipher replaces each letter with its numeric position in the alphabet (A=1, B=2, … Z=26). Configurable delimiter between numbers.",
    category: "cryptography",
    tags: ["a1z26", "numbers", "alphabet", "substitution", "cipher"],
    keywords: ["a1z26 cipher online", "letter number substitution cipher"],
    icon: "ListOrdered",
    status: "new",
    component: () => import("@/tools/cryptography/a1z26"),
    process: (input) => import("@/tools/cryptography/a1z26/logic").then((m) => m.process(input)),
  },
];
